export const syntaxThemes = [
  { name: 'Atom One Dark', css: 'atom-one-dark', dark: true },
  { name: 'Atom One Light', css: 'atom-one-light', dark: false },
  { name: 'GitHub Dark', css: 'github-dark', dark: true },
  { name: 'GitHub', css: 'github', dark: false },
  { name: 'Dracula', css: 'dracula', dark: true },
  { name: 'Monokai', css: 'monokai', dark: true },
  { name: 'Nord', css: 'nord', dark: true },
  { name: 'VS2015', css: 'vs2015', dark: true },
  { name: 'One Dark', css: 'one-dark', dark: true },
  { name: 'Material Dark', css: 'material-dark', dark: true },
  { name: 'Material Ocean', css: 'material-ocean', dark: true },
  { name: 'Material Palenight', css: 'material-palenight', dark: true },
  { name: 'Night Owl', css: 'night-owl', dark: true },
  { name: 'Night Owl Light', css: 'night-owl-light', dark: false },
  { name: 'Obsidian', css: 'obsidian', dark: true },
  { name: 'Ocean', css: 'ocean', dark: true },
  { name: 'Paraiso Dark', css: 'paraiso-dark', dark: true },
  { name: 'Paraiso Light', css: 'paraiso-light', dark: false },
  { name: 'Pygments', css: 'pygments', dark: false },
  { name: 'StackOverflow Dark', css: 'stackoverflow-dark', dark: true },
  { name: 'StackOverflow Light', css: 'stackoverflow-light', dark: false },
  { name: 'Tomorrow Night', css: 'tomorrow-night', dark: true },
  { name: 'XCode', css: 'xcode', dark: false },
  { name: 'Zenburn', css: 'zenburn', dark: true },
];
