export const syntaxThemes = [
  { name: 'ABCDEF', css: 'abcdef', dark: true },
  { name: 'Abyss', css: 'abyss', dark: true },
  { name: 'Android Studio', css: 'androidstudio', dark: true },
  { name: 'Andromeda', css: 'andromeda', dark: true },
  { name: 'Atom One', css: 'atomone', dark: true },
  { name: 'Aura', css: 'aura', dark: true },
  { name: 'Basic Dark', css: 'basic-dark', dark: true },
  { name: 'Basic Light', css: 'basic-light', dark: false },
  { name: 'BBEdit', css: 'bbedit', dark: false },
  { name: 'Bespin', css: 'bespin', dark: true },
  { name: 'Console Dark', css: 'console-dark', dark: true },
  { name: 'Console Light', css: 'console-light', dark: false },
  { name: 'Copilot', css: 'copilot', dark: true },
  { name: 'Darcula', css: 'darcula', dark: true },
  { name: 'Dracula', css: 'dracula', dark: true },
  { name: 'Duotone Dark', css: 'duotone-dark', dark: true },
  { name: 'Duotone Light', css: 'duotone-light', dark: false },
  { name: 'Eclipse', css: 'eclipse', dark: false },
  { name: 'GitHub Dark', css: 'github-dark', dark: true },
  { name: 'GitHub Light', css: 'github', dark: false },
  { name: 'Gruvbox Dark', css: 'gruvbox-dark', dark: true },
  { name: 'Gruvbox Light', css: 'gruvbox-light', dark: false },
  { name: 'Kimbie', css: 'kimbie', dark: true },
  { name: 'Material', css: 'material', dark: true },
  { name: 'Material Dark', css: 'material-dark', dark: true },
  { name: 'Material Light', css: 'material-light', dark: false },
  { name: 'Monokai', css: 'monokai', dark: true },
  { name: 'Monokai Dimmed', css: 'monokai-dimmed', dark: true },
  { name: 'Noctis Lilac', css: 'noctis-lilac', dark: false },
  { name: 'Nord', css: 'nord', dark: true },
  { name: 'Okaidia', css: 'okaidia', dark: true },
  { name: 'Quiet Light', css: 'quietlight', dark: false },
  { name: 'Red', css: 'red', dark: true },
  { name: 'Solarized Dark', css: 'solarized-dark', dark: true },
  { name: 'Solarized Light', css: 'solarized-light', dark: false },
  { name: 'Sublime', css: 'sublime', dark: true },
  { name: 'Tokyo Night', css: 'tokyo-night', dark: true },
  { name: 'Tokyo Night Storm', css: 'tokyo-night-storm', dark: true },
  { name: 'Tokyo Night Day', css: 'tokyo-night-day', dark: false },
  { name: 'Tomorrow Night Blue', css: 'tomorrow-night-blue', dark: true },
  { name: 'VSCode Dark', css: 'vscode-dark', dark: true },
  { name: 'VSCode Light', css: 'vscode-light', dark: false },
  { name: 'White Dark', css: 'white-dark', dark: true },
  { name: 'White Light', css: 'white-light', dark: false },
  { name: 'Xcode Dark', css: 'xcode-dark', dark: true },
  { name: 'Xcode Light', css: 'xcode-light', dark: false },
];
